# Generated by Django 5.2.4 on 2025-07-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_incometype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeType',
            new_name='ExpenseType',
        ),
    ]
