# Generated by Django 5.2.4 on 2025-07-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_defaultexpense_expense_from_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseType',
        ),
    ]
